#define PDA_ATMOS_ALERT		1
#define PDA_FIRE_ALERT		2
#define PDA_POWER_ALERT		4
#define PDA_BURGLAR_ALERT	8
#define PDA_MOTION_ALERT	16
#define PDA_HOTLINE_ALERT	32

#define PDA_SCAN_MEDICAL_HEALTH 	1
#define PDA_SCAN_MEDICAL_REAGENT	2
#define PDA_SCAN_FORENSIC			3
#define PDA_SCAN_REAGENT			4
#define PDA_SCAN_HALOGEN			5
#define PDA_SCAN_GAS				6
#define PDA_SCAN_FLORAL				7
#define PDA_SCAN_POWER				8
#define PDA_SCAN_EXPORT				9

#define PDA_SECURITY_FUNCTIONS		1
#define PDA_ENGINE_FUNCTIONS		2
#define PDA_ATMOS_FUNCTIONS			4
#define PDA_ATMOS_MONITOR_FUNCTIONS	8
#define PDA_MEDICAL_FUNCTIONS		16
#define PDA_MANIFEST_FUNCTIONS		32
#define PDA_JANITOR_FUNCTIONS		64
#define PDA_BOTANY_FUNCTIONS		128
#define PDA_REAGENT_FUNCTIONS		256
#define PDA_NEWSCASTER_FUNCTIONS	512
#define PDA_STATUS_DISPLAY_FUNCTIONS 1024
#define PDA_CARGO_FUNCTIONS			2048
#define PDA_QUARTERMASTER_FUNCTIONS	4096
#define PDA_FORENSIC_FUNCTIONS		8192


#define PDA_SPECIAL_SOFTWARE_FUNCTIONS 	1
#define PDA_SPECIAL_REMOTE_DOOR_FUNCTIONS 2
#define PDA_SPECIAL_DETONATE_FUNCTIONS	4
#define PDA_SPECIAL_CLOWN_FUNCTIONS 	8
#define PDA_SPECIAL_MIME_FUNCTIONS 		16
#define PDA_SPECIAL_SIGNAL_FUNCTIONS 	32
#define PDA_SPECIAL_SLAVE_FUNCTIONS 	64

#define PDA_HOTLINE_CD 2000
