#define MIN_FREE_FREQ 1201
#define MAX_FREE_FREQ 1599

#define MIN_FREQ 1441
#define MAX_FREQ 1489

#define BROADCAST_NORMAL 1
#define BROADCAST_ARTIFICIAL 2
#define BROADCAST_TEST 3

#define BROADCAST_ALL_RADIOS 0
#define BROADCAST_INTERCOMMS_ONLY 1
#define BROADCAST_INTERCOMMS_AND_BOUNCE 2
#define BROADCAST_CENTCOMM_RADIOS 3

#define TRANSMISSION_WIRE	1
#define TRANSMISSION_RADIO	2
#define TRANSMISSION_SUBSPACE 3
