var/list/donor_start_items = list(\
						/obj/item/clothing/head/beanie, \
						/obj/item/clothing/head/bike, \
						/obj/item/clothing/head/hardsuit_helm_clown, \
						/obj/item/clothing/head/cowboy, \
						/obj/item/clothing/head/crusader, \
						/obj/item/clothing/head/cowboy_sheriff, \
						/obj/item/clothing/head/dallas, \
						/obj/item/clothing/head/drinking_hat, \
						/obj/item/clothing/head/microwave, \
						/obj/item/clothing/head/sith_hood, \
						/obj/item/clothing/head/turban, \
						/obj/item/clothing/head/collectable/petehat, \
						/obj/item/clothing/head/collectable/slime, \
						/obj/item/clothing/head/collectable/xenom, \
						/obj/item/clothing/head/collectable/chef, \
						/obj/item/clothing/head/collectable/paper, \
						/obj/item/clothing/head/collectable/tophat, \
						/obj/item/clothing/head/collectable/captain, \
						/obj/item/clothing/head/collectable/police, \
						/obj/item/clothing/head/collectable/welding, \
						/obj/item/clothing/head/collectable/flatcap, \
						/obj/item/clothing/head/collectable/pirate, \
						/obj/item/clothing/head/collectable/kitty, \
						/obj/item/clothing/head/collectable/rabbitears, \
						/obj/item/clothing/head/collectable/wizard, \
						/obj/item/clothing/head/collectable/wizard/red, \
						/obj/item/clothing/head/collectable/wizard/yellow, \
						/obj/item/clothing/head/collectable/wizard/black, \
						/obj/item/clothing/head/collectable/wizard/marisa, \
						/obj/item/clothing/head/collectable/hardhat, \
						/obj/item/clothing/head/collectable/HoS, \
						/obj/item/clothing/head/collectable/thunderdome, \
						/obj/item/clothing/head/collectable/swat, \
						/obj/item/clothing/head/hardhat/cakehat, \
						/obj/item/clothing/head/ushanka, \
						/obj/item/clothing/head/hardhat/pumpkinhead, \
						/obj/item/clothing/head/kitty, \
						/obj/item/clothing/head/hardhat/reindeer, \
						/obj/item/clothing/head/powdered_wig, \
						/obj/item/clothing/head/that, \
						/obj/item/clothing/head/redcoat, \
						/obj/item/clothing/head/mailman, \
						/obj/item/clothing/head/plaguedoctorhat, \
						/obj/item/clothing/head/hasturhood, \
						/obj/item/clothing/head/nursehat, \
						/obj/item/clothing/head/cardborg, \
						/obj/item/clothing/head/justice, \
						/obj/item/clothing/head/rabbitears, \
						/obj/item/clothing/head/flatcap, \
						/obj/item/clothing/head/pirate, \
						/obj/item/clothing/head/hgpiratecap, \
						/obj/item/clothing/head/bowler, \
						/obj/item/clothing/head/witchwig, \
						/obj/item/clothing/head/chicken, \
						/obj/item/clothing/head/fedora, \
						/obj/item/clothing/head/sombrero, \
						/obj/item/clothing/head/sombrero/green, \
						/obj/item/clothing/head/cone, \
						/obj/item/clothing/head/collectable/beret, \
						/obj/item/clothing/head/crown, \
						/obj/item/clothing/head/flowerpower, \
						/obj/item/clothing/head/outback, \
						/obj/item/clothing/head/wizard/marisa/fake, \
						/obj/item/clothing/suit/cloak/sith_cloak, \
						/obj/item/clothing/suit/armor/sith_suit, \
						/obj/item/clothing/suit/armor/hardsuit_clown, \
						/obj/item/clothing/shoes/fuzzy_slippers
						)

var/list/donor_pdas = list("Normal", "Transparent", "Pip Boy", "Rainbow")
